In [2]:
r"C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv"

'C:\\Users\\Rahul\\Downloads\\archive(3)\\Algerian_forest_fires_dataset.csv'

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
# from sklearn.datasets import load_algeria

In [11]:
df = pd.read_csv(r"C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv")
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [13]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [14]:
from sklearn.model_selection import train_test_spilit

X_train, X_test, y_train, y_test = train_test_spilit(X, y, test_size=0.30, random_state=42)

ImportError: cannot import name 'train_test_spilit' from 'sklearn.model_selection' (C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\model_selection\__init__.py)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

NameError: name 'X' is not defined

In [17]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv(r"C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv")
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [20]:
X = df.iloc[:0:1].values
y = df.iloc[:,1].values

In [21]:
print(X.shape)
print(y.shape)

(0, 14)
(247,)

In [25]:
from sklearn.model_selection import train_test_spilit
X_train,X_test,y_train,y_test = train_test_spilit(X,y,test_size=0.2)

ImportError: cannot import name 'train_test_spilit' from 'sklearn.model_selection' (C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\model_selection\__init__.py)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

ValueError: Found input variables with inconsistent numbers of samples: [0, 247]

In [28]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Classes'])  # Features
y = df['Classes']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Now you can use X_train, X_test, y_train, y_test in your machine learning models

KeyError: "['Classes'] not found in axis"

In [32]:
X = df.drop(['Classes'], axis =0)

KeyError: "['Classes'] not found in axis"

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline
import warnings
warnings.simplefilter("ignore")
# from skleran.dataset import load_boston
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

In [34]:
df = pd.read_csv(r"C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv")
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [38]:
x = df.iloc[:,:-1]
x

    day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  FWI
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7    0
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9  0.5
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...  ...
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5

[247 rows x 13 columns]

In [47]:

y = df.iloc[:,-1]
y

0       not fire
1       not fire
2       not fire
3       not fire
4       not fire
           ...
242         fire
243     not fire
244     not fire
245     not fire
246    not fire
Name: Classes  , Length: 247, dtype: object

In [48]:
# train test spilit
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [49]:
lin_model = LinearRegression()

In [2]:
lin_model.fit(x_train,y_train)
lin_model.predict(x_test,y_train)

NameError: name 'lin_model' is not defined

In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Load the dataset from CSV file
df = pd.read_csv(r'C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv')
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [93]:
df = df.drop(columns=["Classes"])

KeyError: "['Classes'] not found in axis"

In [92]:

df.pop("Classes")

KeyError: 'Classes'

In [67]:
x = df.iloc[:,:-1]
x

    day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  FWI
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7    0
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9  0.5
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...  ...
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5

[247 rows x 13 columns]

In [68]:
X = df.drop(columns=['Classes'])

KeyError: "['Classes'] not found in axis"

In [71]:
# Drop the 'Classes' column from the DataFrame
df = df.drop(['Classes'], axis=1)

KeyError: "['Classes'] not found in axis"

In [72]:
# Drop the 'Classes' column from the DataFrame
df.drop(columns=['Classes'], inplace=True)

KeyError: "['Classes'] not found in axis"

In [78]:
# Drop the 'Classes' column from the DataFrame and assign the result back to df
df = df.drop(['Classes']),axis=1

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3953576900.py, line 2)

In [79]:
from sklearn.linear_model import Ridge

In [82]:
from sklearn.model_selection import GridSearchCV

In [85]:
ridge_regressor = Ridge()

In [86]:
ridge_regressor

Ridge()

In [87]:
parameter = {'alpha':[1,2,5,10,20,30,40,50,60,70,80,90]}
ridgecv = GridSearchCV(ridge_regressor, parameter, scoring = 'neg_mean_squared_error', cv = 5)
ridgecv.fit(x_train, y_train)

ValueError:
All the 60 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
48 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1134, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1147, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 917, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 380, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\AppData\Roaming\Python\Python311\site-packages\pandas\core\generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'day'

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1134, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\base.py", line 621, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1147, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 917, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 380, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rahul\AppData\Roaming\Python\Python311\site-packages\pandas\core\generic.py", line 2084, in __array__
    arr = np.asarray(values, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '14.6 9'

In [89]:
df.pop("Classes")

KeyError: 'Classes'

In [98]:
df = pd.read_csv(r'C:\Users\Rahul\Downloads\archive(3)\Algerian_forest_fires_dataset.csv')
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [103]:
df.drop(labels='Classes  ', axis=1)

    day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  FWI
0     1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5
1     2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4
2     3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1
3     4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7    0
4     5     6  2012          27  77  16     0  64.8    3  14.2  1.2   3.9  0.5
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...  ...
242  26     9  2012          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5
243  27     9  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0
244  28     9  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5

[247 rows x 13 columns]

In [101]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  '],
      dtype='object')